### ISSUE TITLE
To much CPU consumtion

### ISSUE THREAD

**Issue by rokir** [schomery/tab-memory-usage#3]
Hello!
I've use a 2 windows and a 362 opened tabs.
Have installed these extensions:
SessionManager
AdblockPlus
BarTab Heavy
FlashStopper
LastPass
LocaLink
SpeedyFox
Tree Style Tab
Xmarks
and Tab Memory Usage
FF 41.0b7

Screenshots when extension is On and Off
![tabmemon](https://cloud.githubusercontent.com/assets/14175956/9729844/081dee2a-561b-11e5-9da2-29665e70405f.PNG)
![tabmemoff](https://cloud.githubusercontent.com/assets/14175956/9729845/081e4000-561b-11e5-9221-97eaeec11275.PNG)

CPU consumption is about a 17% and feeling heavy lags on FF UI.

WBR Kirill

**Comment by schomery** [comment]
I guess since you have many open tabs, the extension has to calculate memory usage a lot and this causes high CPU usage.

I added a new option to the latest dev version. In this version you can change the minimum time delay between two memory calculations for a single tab. Try to increase the number to 15 seconds and see how it affects the performance of the extension.

https://github.com/schomery/tab-memory-usage/blob/master/src/executables/extension.xpi?raw=true

download the XPI and drop it into your Firefox.

**Comment by rokir** [comment]
Thank you!
Version 0.1.9 works very well!
I'm using 30 seconds delay.
